version: '2'
networks: 
 bot:
  driver: bridge
services:
 bot:
  networks: 
   - bot
  container_name: bot
  environment: 
   - TOKEN=TOKEN
   - OWNERID=ID
   - PREFIXES=!,-								# Separate the prefix with comma. Comma is not allowed as prefix.
   - MONGOURL=mongodb://mongo:27017/gbot
  image: burger38/gbot
  command: npm start
  restart: always
 lava:
  networks: 
   - bot
  container_name: lava
  restart: always
  image: burger38/lavalink
  environment: 
   - LAVALINK_SERVER_BUFFER_DURATION_MS=400
   - LAVALINK_SERVER_PASSWORD=password
   - LAVALINK_SERVER_SOURCES_BANDCAMP=true
   - LAVALINK_SERVER_SOURCES_HTTP=true
   - LAVALINK_SERVER_SOURCES_LOCAL=false
   - LAVALINK_SERVER_SOURCES_MIXER=true
   - LAVALINK_SERVER_SOURCES_SOUNDCLOUD=true
   - LAVALINK_SERVER_SOURCES_TWITCH=true
   - LAVALINK_SERVER_SOURCES_VIMEO=true
   - LAVALINK_SERVER_SOURCES_YOUTUBE=true
   - LAVALINK_SERVER_WS_HOST=0.0.0.0
   - LAVALINK_SERVER_WS_PORT=80
   - LAVALINK_SERVER_YOUTUBE_PLAYLIST_LOAD_LIMIT=600
   - SERVER_ADDRESS=0.0.0.0
   - SERVER_PORT=2333
 mongo:
  container_name: mongo
  restart: always
  image: mongo
  volumes: 
   - /opt/mongodb:/data/db
  networks: 
   - bot
  ports: 
   - 27017:27017
 mongo-express: 
  restart: always
  image: mongo-express
  environment: 
   - ME_CONFIG_BASICAUTH_USERNAME=gbot
   - ME_CONFIG_BASICAUTH_PASSWORD=password
   - ME_CONFIG_MONGODB_PORT=27017
   - ME_CONFIG_MONGODB_SERVER=mongo