version: '2.4'

networks: 
  bot:
    driver: bridge

services: 
  bot:
    image: burger38/gbot
    container_name: bot
    command: npm start
    restart: always
    environment: 
      - TOKEN=Token
      - OWNERID=ID
      - PREFIXES=!,-  # Separate the prefix with comma. Comma is not allowed as prefix.
      - MONGOURL=mongodb://db:27017/gbot
    networks: 
      - bot

  db:
    image: mongo
    container_name: db
    restart: always
    volumes: 
      - /bot/db:/data/db
    ports: 
      - 27017:27017
    networks: 
      - bot

  express:
    image: mongo-express
    container_name: express
    restart: always
    environment: 
      - ME_CONFIG_BASICAUTH_USERNAME=gbot
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=db
    ports: 
      - 8091:8081
    networks: 
      - bot

  lava:
    image: burger38/lavalink
    container_name: lava
    restart: always
    environment: 
      - LAVALINK_SERVER_BUFFER_DURATION_MS=400
      - LAVALINK_SERVER_PASSWORD=password
      - LAVALINK_SERVER_SOURCES_BANDCAMP=true
      - LAVALINK_SERVER_SOURCES_HTTP=true
      - LAVALINK_SERVER_SOURCES_LOCAL=false
      - LAVALINK_SERVER_SOURCES_MIXER=true
      - LAVALINK_SERVER_SOURCES_SOUNDCLOUD=true
      - LAVALINK_SERVER_SOURCES_TWITCH=true
      - LAVALINK_SERVER_SOURCES_VIMEO=true
      - LAVALINK_SERVER_SOURCES_YOUTUBE=true
      - LAVALINK_SERVER_WS_HOST=0.0.0.0
      - LAVALINK_SERVER_WS_PORT=80
      - LAVALINK_SERVER_YOUTUBE_PLAYLIST_LOAD_LIMIT=600
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=2333
    networks: 
      - bot